02333 Tasks B5 and A5: src/program_1/main.c File Reference
src/program_1/main.c File Reference
The second user program - in a neverending loop, sends a message to process 0 and waits for a reply.
#include <scwrapper.h>
Functions
void main (int argc, char *argv[])
Variables
char findport_process_failed [] = "process n: findport on my own port failed\n"
char findport_process0_failed [] = "process n: findport for process 0 failed\n"
char sending_ping [] = "process n: sending ping\n"
char send_failed [] = "process n: send failed\n"
char recv_failed [] = "process n: receive failed\n"
char recvd_pong [] = "process n: received pong\n"
char test_failed [] = "process n: message test failed\n"
Detailed Description
The second user program - in a neverending loop, sends a message to process 0 and waits for a reply.
When the test case runs, there will be two instances of this program running.
Definition in file main.c.
Function Documentation
void main (int argc, char * argv[])
Definition at line 23 of file main.c.
References ALL_OK, debugger(), findport(), findport_process0_failed, findport_process_failed, getpid(), prints(), message::quad_0, message::quad_1, message::quad_2, message::quad_3, message::quad_4, message::quad_5, message::quad_6, message::quad_7, receive(), recv_failed, recvd_pong, send(), send_failed, sending_ping, SYSCALL_MSG_SHORT, and test_failed.
{
 long send_port, recv_port;
 long my_pid;
 char pidchar;
 my_pid = getpid();
 if (my_pid<0)
 {
  prints("Can not get my PID!");
  debugger();
 }
 /* Setup the strings, replacing "n" with the actual process identity. */
 /* Convert my_pid to a character. */
 pidchar = '0' + (char) my_pid;
 /* And insert on the 9th place in the char arrays. */
 findport_process_failed[8]     = pidchar;
 findport_process0_failed[8]    = pidchar;
 sending_ping[8]                                = pidchar;
 send_failed[8]                                 = pidchar;
 recv_failed[8]                                 = pidchar;
 recvd_pong[8]                                  = pidchar;
 test_failed[8]                                 = pidchar;
 /* Get the port index for our own port 0. */
 recv_port=findport(0,my_pid);
 if (recv_port < 0)
 {
  prints(findport_process_failed);
  debugger();
 }
 /* Get the port index for process 0's port 0. */
 send_port=findport(0,0);
 if (send_port < 0)
 {
  prints(findport_process0_failed);
  debugger();
 }
 /* Go into an infinite loop, sending messages and waiting for replies. */
 while(1)
 {
  struct message msg;
  unsigned long  sender, type;
  msg.quad_0=0;
  msg.quad_1=1;
  msg.quad_2=2;
  msg.quad_3=3;
  msg.quad_4=4;
  msg.quad_5=5;
  msg.quad_6=6;
  msg.quad_7=7;
  prints(sending_ping);
  if (ALL_OK != send(send_port, &msg))
  {
   prints(send_failed);
   debugger();
  }
  if ((ALL_OK != receive(recv_port, &msg, &sender, &type)) ||
      (SYSCALL_MSG_SHORT != type) ||
      (0 != sender))
  {
   prints(recv_failed);
   debugger();
  }
  /* Test message validity. */
  if ((7 != msg.quad_0) ||
      (6 != msg.quad_1) ||
      (5 != msg.quad_2) ||
      (4 != msg.quad_3) ||
      (3 != msg.quad_4) ||
      (2 != msg.quad_5) ||
      (1 != msg.quad_6) ||
      (0 != msg.quad_7))
  {
   prints(test_failed);
   debugger();
  }
  prints(recvd_pong);
  debugger();
 }
}
Variable Documentation
char findport_process0_failed[] = "process n: findport for process 0 failed\n"
Definition at line 15 of file main.c.
Referenced by main().
char findport_process_failed[] = "process n: findport on my own port failed\n"
Definition at line 14 of file main.c.
Referenced by main().
char recv_failed[] = "process n: receive failed\n"
Definition at line 18 of file main.c.
Referenced by main().
char recvd_pong[] = "process n: received pong\n"
Definition at line 19 of file main.c.
Referenced by main().
char send_failed[] = "process n: send failed\n"
Definition at line 17 of file main.c.
Referenced by main().
char sending_ping[] = "process n: sending ping\n"
Definition at line 16 of file main.c.
Referenced by main().
char test_failed[] = "process n: message test failed\n"
Definition at line 20 of file main.c.
Referenced by main().