/* Generated By:JavaCC: Do not edit this line. RulesConstants.java */
package rule.engine;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RulesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"||\"",
    "\"&&\"",
    "\">=\"",
    "\"==\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"when\"",
    "\"if\"",
    "\"then\"",
    "<IDENTIFIER>",
    "<NUMBER>",
  };

}
