02333 Tasks B4 and A4: src/include/scwrapper.h File Reference
src/include/scwrapper.h File Reference
This file contains C wrapper functions for system calls.
#include "sysdefines.h"
Functions
static unsigned long version (void)
Wrapper for the system call that returns the version of the kernel.
static long prints (const char *const string)
Wrapper for the system call that prints a string.
static long printhex (const unsigned long value)
Wrapper for the system call that prints a hexadecimal value.
static long debugger (void)
Wrapper for the system call that invokes the bochs debugger.
static void terminate (void)
Wrapper for the system call that terminates threads and processes.
static long createprocess (const int executable)
Wrapper for the system call that creates processes.
static long pause (const int ticks)
Wrapper for the system call that pauses the process for a specified number of ticks.
static long time (void)
Wrapper for the system call that returns the current system time in ticks.
static long alloc (unsigned long length, int flags)
Wrapper for the system call that allocates a memory block.
static long free (unsigned long address)
Wrapper for the system call that frees a memory block.
Detailed Description
This file contains C wrapper functions for system calls.
The wrappers are used by user programs to perform system calls from C.
Definition in file scwrapper.h.
Function Documentation
static long alloc (unsigned long length, int flags) [inline, static]
Wrapper for the system call that allocates a memory block.
Parameters:
length integer holding the number of bytes to allocate
flags integer holding the type of memory block to allocate
Definition at line 126 of file scwrapper.h.
References SYSCALL_ALLOCATE.
Referenced by main().
{
 long return_value;
 __asm volatile("syscall" :
                 "=a" (return_value) :
                 "a" (SYSCALL_ALLOCATE), "D" (length), "S" (flags) :
                 "cc", "%r11", "%rcx");
 return return_value;
}
static long createprocess (const int executable) [inline, static]
Wrapper for the system call that creates processes.
Parameters:
executable integer identifying the program which should be loaded and run as a process.
Definition at line 81 of file scwrapper.h.
References SYSCALL_CREATEPROCESS.
{
 long return_value;
 __asm volatile("syscall" :
                 "=a" (return_value) :
                 "a" (SYSCALL_CREATEPROCESS), "D" (executable) :
                 "cc", "%r11", "%rcx");
 return return_value;
}
static long debugger (void) [inline, static]
Wrapper for the system call that invokes the bochs debugger.
Definition at line 56 of file scwrapper.h.
References SYSCALL_DEBUGGER.
{
 long return_value;
 __asm volatile("syscall" :
                 "=a" (return_value) :
                 "a" (SYSCALL_DEBUGGER) :
                 "cc", "%rcx", "%r11");
 return return_value;
}
static long free (unsigned long address) [inline, static]
Wrapper for the system call that frees a memory block.
Parameters:
address address to the memory block to free.
Definition at line 140 of file scwrapper.h.
References SYSCALL_FREE.
Referenced by main().
{
 long return_value;
 __asm volatile("syscall" :
                 "=a" (return_value) :
                 "a" (SYSCALL_FREE), "D" (address) :
                 "cc", "%r11", "%rcx");
 return return_value;
}
static long pause (const int ticks) [inline, static]
Wrapper for the system call that pauses the process for a specified number of ticks.
Parameters:
ticks integer holding the number of ticks the process should be paused.
Definition at line 97 of file scwrapper.h.
References SYSCALL_PAUSE.
{
 long return_value;
 __asm volatile("syscall" :
                 "=a" (return_value) :
                 "a" (SYSCALL_PAUSE), "D" (ticks) :
                 "cc", "%r11", "%rcx");
 return return_value;
}
static long printhex (const unsigned long value) [inline, static]
Wrapper for the system call that prints a hexadecimal value.
Parameters:
value hexadecimal value to be printed.
Definition at line 44 of file scwrapper.h.
References SYSCALL_PRINTHEX.
{
 long return_value;
 __asm volatile("syscall" :
                 "=a" (return_value) :
                 "a" (SYSCALL_PRINTHEX), "D" (value) :
                 "cc", "%rcx", "%r11");
 return return_value;
}
static long prints (const char *const string) [inline, static]
Wrapper for the system call that prints a string.
Parameters:
string Pointer to the string to be printed.
Definition at line 30 of file scwrapper.h.
References SYSCALL_PRINTS.
Referenced by main().
{
 long return_value;
 __asm volatile("syscall" :
                 "=a" (return_value) :
                 "a" (SYSCALL_PRINTS), "D" (string) :
                 "cc", "%rcx", "%r11");
 return return_value;
}
static void terminate (void) [inline, static]
Wrapper for the system call that terminates threads and processes.
Definition at line 68 of file scwrapper.h.
References SYSCALL_TERMINATE.
{
 __asm volatile("syscall" :
                 :
                 "a" (SYSCALL_TERMINATE) :
                 "cc", "%rcx", "%r11");
}
static long time (void) [inline, static]
Wrapper for the system call that returns the current system time in ticks.
Definition at line 111 of file scwrapper.h.
References SYSCALL_TIME.
{
 long return_value;
 __asm volatile("syscall" :
                 "=a" (return_value) :
                 "a" (SYSCALL_TIME) :
                 "cc", "%rcx", "%r11");
 return return_value;
}
static unsigned long version (void) [inline, static]
Wrapper for the system call that returns the version of the kernel.
Definition at line 16 of file scwrapper.h.
References SYSCALL_VERSION.
{
 unsigned long return_value;
 __asm volatile("syscall" :
                 "=a" (return_value) :
                 "a" (SYSCALL_VERSION) :
                 "cc", "%rcx", "%r11");
 return return_value;
}