<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/NiceViewWSDL/NiceViewWSDL" xmlns:ns="http:/niceview.ws" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="NiceViewWSDL" targetNamespace="http:/niceview.ws">
<wsdl:import namespace="http:/niceview.ws" location="NiceViewWSDL.wsdl"/>
<wsdl:binding name="NiceViewWSDLBinding" type="ns:NiceViewWSDLPortType">
<soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
<wsdl:operation name="bookHotel">
<soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="bookHotel_action"/>
<wsdl:input name="input2">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http:/niceview.ws" use="literal"/>
</wsdl:input>
<wsdl:output name="output2">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http:/niceview.ws" use="literal"/>
</wsdl:output>
<wsdl:fault name="fault1">
<soap:fault xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="fault1" use="literal"/>
</wsdl:fault>
</wsdl:operation>
<wsdl:operation name="cancelHotel">
<soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="cancelHotel_action"/>
<wsdl:input name="input3">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http:/niceview.ws" use="literal"/>
</wsdl:input>
<wsdl:output name="output3">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http:/niceview.ws" use="literal"/>
</wsdl:output>
<wsdl:fault name="fault1">
<soap:fault xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="fault1" use="literal"/>
</wsdl:fault>
</wsdl:operation>
<wsdl:operation name="getHotels">
<soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="getHotels_action"/>
<wsdl:input name="input1">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http:/niceview.ws" use="literal"/>
</wsdl:input>
<wsdl:output name="output1">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http:/niceview.ws" use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="NiceViewWSDLService">
<wsdl:port name="NiceViewWSDLPort" binding="ns:NiceViewWSDLBinding">
<soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="REPLACE_WITH_ACTUAL_URL"/>
</wsdl:port>
</wsdl:service>
</definitions>
