<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Metro/2.1.1 (branches/2.1-6844; 2011-07-29T12:07:24+0000) JAXWS-RI/2.2.5 JAXWS/2.2. --><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://lameduck.dtu.ws" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="LameDuckWrapper" targetNamespace="http://lameduck.dtu.ws">
    <import namespace="http://lameduck.dtu.ws" location="http://localhost:8080/LameDuck/LameDuckService?wsdl=1"/>

    <binding name="LameDuckPortTypeBinding" type="tns:LameDuckPortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
        <operation name="getFlights">
            <soap:operation soapAction="getFlights_action"/>
            <input name="input1">
                <soap:body namespace="http://lameduck.dtu.ws" use="literal"/>
            </input>
            <output name="output1">
                <soap:body namespace="http://lameduck.dtu.ws" use="literal"/>
            </output>
        </operation>
        <operation name="bookFlight">
            <soap:operation soapAction="bookFlight_action"/>
            <input name="input2">
                <soap:body namespace="http://lameduck.dtu.ws" use="literal"/>
            </input>
            <output name="output2">
                <soap:body namespace="http://lameduck.dtu.ws" use="literal"/>
            </output>
            <fault name="fault1">
                <soap:fault name="fault1"/>
            </fault>             
        </operation>
        <operation name="cancelFlight">
            <soap:operation soapAction="cancelFlight_action"/>
            <input name="input3">
                <soap:body namespace="http://lameduck.dtu.ws" use="literal"/>
            </input>
            <output name="output3">
                <soap:body namespace="http://lameduck.dtu.ws" use="literal"/>
            </output>
            <fault name="fault2">
                <soap:fault name="fault2"/>
            </fault>             
        </operation>
    </binding>
    
    <service name="LameDuckService">
        <port name="LameDuckPortTypeBindingPort" binding="tns:LameDuckPortTypeBinding">
            <soap:address location="http://localhost:8080/LameDuck/LameDuckService"/>
        </port>
    </service>

    <plnk:partnerLinkType name="LameDuckWrapper">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
        In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
        A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="LameDuckPortTypeRole" portType="tns:LameDuckPortType"/>
    </plnk:partnerLinkType>
</definitions>