02333 Tasks B6 and A6: src/program_0/main.c File Reference
src/program_0/main.c File Reference
The first user program - the test case follows the structure of the producer consumer example in Tanenbaum&Woodhull's book.
#include <scwrapper.h>
Functions
void thread (void)
void main (int argc, char *argv[])
Variables
long buffer [16]
int head = 0
int tail = 0
long empty_semaphore_handle
long mutex_semaphore_handle
long full_semaphore_handle
Detailed Description
The first user program - the test case follows the structure of the producer consumer example in Tanenbaum&Woodhull's book.
Definition in file main.c.
Function Documentation
void main (int argc, char * argv[])
Definition at line 60 of file main.c.
References ALL_OK, alloc(), buffer, createsemaphore(), createthread(), empty_semaphore_handle, full_semaphore_handle, head, mutex_semaphore_handle, prints(), semaphoredown(), and semaphoreup().
{
 register long  counter=0;
 register long  thread_stack;
 empty_semaphore_handle=createsemaphore(16);
 if (empty_semaphore_handle<0)
 {
  prints("createsemaphore failed!\n");
  return;
 }
 full_semaphore_handle=createsemaphore(0);
 if (full_semaphore_handle<0)
 {
  prints("createsemaphore failed!\n");
  return;
 }
 mutex_semaphore_handle=createsemaphore(1);
 if (mutex_semaphore_handle<0)
 {
  prints("createsemaphore failed!\n");
  return;
 }
 thread_stack=alloc(4096, 0);
 if (0 >= thread_stack)
 {
  prints("Could not allocate the thread's stack!\n");
  return;
 }
 if (ALL_OK != createthread(thread, thread_stack+4096))
 {
  prints("createthread failed!\n");
  return;
 }
 /* This is the producer. */
 while(1)
 {
  if (ALL_OK != semaphoredown(empty_semaphore_handle))
  {
   prints("semaphoredown failed!\n");
   break;
  }
  if (ALL_OK != semaphoredown(mutex_semaphore_handle))
  {
   prints("semaphoredown failed!\n");
   break;
  }
  buffer[head]=counter++;
  head=(head+1)&15;
  if (ALL_OK != semaphoreup(mutex_semaphore_handle))
  {
   prints("semaphoreup failed!\n");
   break;
  }
  if (ALL_OK != semaphoreup(full_semaphore_handle))
  {
   prints("semaphoreup failed!\n");
   break;
  }
 }
}
void thread (void)
Definition at line 18 of file main.c.
References ALL_OK, buffer, empty_semaphore_handle, full_semaphore_handle, mutex_semaphore_handle, printhex(), prints(), semaphoredown(), semaphoreup(), tail, and terminate().
{
 /* This is the consumer. */
 while(1)
 {
  long value;
  if (ALL_OK != semaphoredown(full_semaphore_handle))
  {
   prints("semaphoredown failed!\n");
   break;
  }
  if (ALL_OK != semaphoredown(mutex_semaphore_handle))
  {
   prints("semaphoredown failed!\n");
   break;
  }
  value=buffer[tail];
  tail=(tail+1)&15;
  if (ALL_OK != semaphoreup(mutex_semaphore_handle))
  {
   prints("semaphoreup failed!\n");
   break;
  }
  if (ALL_OK != semaphoreup(empty_semaphore_handle))
  {
   prints("semaphoreup failed!\n");
   break;
  }
  printhex(value);
  prints("\n");
 }
 terminate();
}
Variable Documentation
long buffer[16]
Definition at line 10 of file main.c.
Referenced by main(), and thread().
long empty_semaphore_handle
Definition at line 14 of file main.c.
Referenced by main(), and thread().
long full_semaphore_handle
Definition at line 16 of file main.c.
Referenced by main(), and thread().
int head = 0
Definition at line 11 of file main.c.
Referenced by main().
long mutex_semaphore_handle
Definition at line 15 of file main.c.
Referenced by main(), and thread().
int tail = 0
Definition at line 12 of file main.c.
Referenced by thread().