02333 Task 7: src/kernel/kernel.c File Reference
src/kernel/kernel.c File Reference
This is the main source code for the kernel.
#include "kernel.h"
#include <sysdefines.h>
#include "kernel.h"
#include "threadqueue.h"
Data Structures
struct prepare_process_return_value
Helper struct that is used to return values from prepare_process.
Defines
#define KEYBOARD_BUFFER_SIZE 16
Size of the keyboard scan code buffer.
Functions
static struct
prepare_process_return_value prepare_process (const struct Elf64_Ehdr *elf_image, const unsigned int process, unsigned long memory_footprint_size)
Copies an ELF image to memory and prepares a process.
static void cleanup_process (const int process)
This is the last thing that is run when a process terminates.
void initialize (void)
This fuction initializes the kernel after the assembly code portion has set the system and the CPU up.
static int allocate_thread (void)
Allocate one thread.
static void keyboard_interrupt_handler (void)
Keyboard interrupt handler.
void interrupt_dispatcher (const unsigned long interrupt_number)
This function gets called from the interrupt handler and dispatches interrupts to interrupt handlers.
Variables
union thread thread_table [MAX_NUMBER_OF_THREADS]
Array holding all threads in the systems.
struct process process_table [MAX_NUMBER_OF_PROCESSES]
Array holding all processes in the system.
struct thread_queue ready_queue
The ready queue.
static struct executable executable_table [MAX_NUMBER_OF_PROCESSES]
Array holding descriptions of all executable programs.
static int executable_table_size = 0
The number of executable programs in the executable_table.
struct executable_image *const ELF_images_start
The first executable image in the linked list of executable images.
const char *const ELF_images_end
The address of the first byte after the end of the last ELF image.
int timer_queue_head = -1
The index, into thread_table, of the head of the timer queue.
long system_time = 0
This variable holds the current system time.
static unsigned char keyboard_scancode_buffer [KEYBOARD_BUFFER_SIZE]
Buffer which holds the keyboard scan codes coming from the keyboard interrupt handler.
static int keyboard_scancode_low_marker = 0
Low water mark for the scan code buffer.
static int keyboard_scancode_high_marker = 0
High water mark for the scan code buffer.
struct thread_queue keyboard_blocked_threads
List of threads blocked waiting for scan codes.
Detailed Description
This is the main source code for the kernel.
Here all important variables will be initialized.
Definition in file kernel.c.
Define Documentation
#define KEYBOARD_BUFFER_SIZE 16
Size of the keyboard scan code buffer.
Definition at line 48 of file kernel.c.
Referenced by keyboard_interrupt_handler().
Function Documentation
static int allocate_thread (void) [inline, static]
Allocate one thread.
The allocated thread is not initialized. Rip and rflags need to be set for the thread to start properly.
Returns:
An index into thread_table or -1 if no thread could be allocated.
Definition at line 647 of file kernel.c.
References MAX_NUMBER_OF_THREADS, thread::owner, and thread_table.
{
 register int i;
 /* loop over all threads and find a free thread. */
 for(i=0; i<MAX_NUMBER_OF_THREADS; i++)
 {
  /* An owner index of -1 means that the thread is available. */
  if (-1 == thread_table[i].data.owner)
  {
   return i;
  }
 }
 /* We return -1 to indicate that there are no available threads. */
 return -1;
}
static void cleanup_process (const int process) [static]
This is the last thing that is run when a process terminates.
Parameters:
process The index, into process_table, of the terminating process.
Definition at line 235 of file kernel.c.
References cpu_private_data, page_frame::free_is_allowed, kernel_page_table_root, memory_pages, page_frame::owner, page_frame_table, and CPU_private::page_table_root.
{
 register unsigned int i;
 for(i=0; i<memory_pages; i++)
 {
  if (page_frame_table[i].owner == process)
  {
   page_frame_table[i].owner=-1;
   page_frame_table[i].free_is_allowed=1;
  }
 }
 cpu_private_data.page_table_root = kernel_page_table_root;
}
void initialize (void)
This fuction initializes the kernel after the assembly code portion has set the system and the CPU up.
Definition at line 253 of file kernel.c.
References allocate_port(), clear_screen(), cpu_private_data, thread::data, Elf64_Ehdr::e_ehsize, Elf64_Ehdr::e_flags, Elf64_Ehdr::e_ident, Elf64_Ehdr::e_machine, Elf32_Ehdr::e_phoff, Elf64_Ehdr::e_type, Elf64_Ehdr::e_version, EI_CLASS, EI_DATA, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, EI_VERSION, executable::elf_image, executable_image::elf_image, ELF_images_end, executable_table, executable_table_size, first_available_memory_byte, prepare_process_return_value::first_instruction_address, page_frame::free_is_allowed, inb(), initialize_memory_protection(), initialize_ports(), initialize_thread_synchronization(), context::integer_registers, kernel_page_table_root, keyboard_blocked_threads, kprinthex(), kprints(), MAX_NUMBER_OF_FRAMES, MAX_NUMBER_OF_PROCESSES, MAX_NUMBER_OF_THREADS, executable::memory_footprint_size, memory_pages, memory_size, executable_image::next, outb(), page_frame::owner, thread::owner, Elf64_Phdr::p_filesz, Elf64_Phdr::p_flags, Elf64_Phdr::p_memsz, Elf64_Phdr::p_offset, Elf64_Phdr::p_type, Elf64_Phdr::p_vaddr, page_frame_table, prepare_process_return_value::page_table_address, CPU_private::page_table_root, process::page_table_root, process::parent, PF_KERNEL, prepare_process(), process_table, PT_LOAD, PT_NULL, PT_PHDR, ready_queue, thread::registers, context::rflags, context::rip, CPU_private::thread_index, thread_queue_init(), thread_table, process::threads, and update_memory_protection().
{
 register int i;
 /* Loop over all threads in the thread table and reset the owner. */
 for(i=0; i<MAX_NUMBER_OF_THREADS; i++)
 {
  thread_table[i].data.owner=-1; /* -1 is an illegal process_table index.
                                     We use that to show that the thread
                                     is dormant. */
 }
 /* Loop over all processes in the thread table and mark them as not
    executing. */
 for(i=0; i<MAX_NUMBER_OF_PROCESSES; i++)
 {
  process_table[i].threads=0;    /* No executing process has less than 1
                                    thread. */
 }
 /* Initialize the ready queue. */
 thread_queue_init(&ready_queue);
 /* Initialize the list of blocked threads waiting for the keyboard. */
 thread_queue_init(&keyboard_blocked_threads);
 /* Calculate the number of pages. */
 memory_pages = memory_size/(4*1024);
 {
  /* Calculate the number of frames occupied by the kernel and executable
     images. */
  const register int k=first_available_memory_byte/(4*1024);
  /* Mark the pages that are used by the kernel or executable images as taken
    by the kernel (-2 in the owner field). */
  for(i=0; i<k; i++)
  {
   page_frame_table[i].owner=-2;
   page_frame_table[i].free_is_allowed=0;
  }
  /* Loop over all the rest page frames and mark them as free (-1 in owner
     field). */
  for(i=k; i<memory_pages; i++)
  {
   page_frame_table[i].owner=-1;
   page_frame_table[i].free_is_allowed=1;
  }
  /* Mark any unusable pages as taken by the kernel. */
  for(i=memory_pages; i<MAX_NUMBER_OF_FRAMES; i++)
  {
   page_frame_table[i].owner=-2;
   page_frame_table[i].free_is_allowed=0;
  }
 }
 /* Go through the linked list of executable images and verify that they
    are correct. At the same time build the executable_table. */
 {
  const struct executable_image* image;
  for (image=ELF_images_start; 0!=image; image=image->next)
  {
   unsigned long      image_size;
   /* First calculate the size of the image. */
   if (0 != image->next)
   {
    image_size = ((char *) (image->next)) - ((char *) image) -1;
   }
   else
   {
    image_size = ((char *) ELF_images_end) - ((char *) image) - 1;
   }
   /* Check that the image is an ELF image and that it is of the
      right type. */
   if (
       /* EI_MAG0 - EI_MAG3 have to be 0x7f 'E' 'L' 'F'. */
       (image->elf_image.e_ident[EI_MAG0] != 0x7f) ||
       (image->elf_image.e_ident[EI_MAG1] != 'E') ||
       (image->elf_image.e_ident[EI_MAG2] != 'L') ||
       (image->elf_image.e_ident[EI_MAG3] != 'F') ||
       /* Check that the image is a 64-bit image. */
       (image->elf_image.e_ident[EI_CLASS] != 2) ||
       /* Check that the image is a little endian image. */
       (image->elf_image.e_ident[EI_DATA] != 1) ||
       /* And that the version of the image format is correct. */
       (image->elf_image.e_ident[EI_VERSION] != 1) ||
       /* NB: We do not check the ABI or ABI version. We really should
          but currently those fields are not set properly by the build
          tools. They are both set to zero which means: System V ABI,
          third edition. However, the ABI used is clearly not System V :-) */
       /* Check that the image is executable. */
       (image->elf_image.e_type != 2) ||
       /* Check that the image is executable on AMD64. */
       (image->elf_image.e_machine != 0x3e) ||
       /* Check that the object format is corrent. */
       (image->elf_image.e_version != 1) ||
       /* Check that the processor dependent flags are all reset. */
       (image->elf_image.e_flags != 0) ||
       /* Check that the length of t   he header is what we expect. */
       (image->elf_image.e_ehsize != sizeof(struct Elf64_Ehdr)) ||
       /* Check that the size of the program header table entry is what
          we expect. */
       (image->elf_image.e_phentsize != sizeof(struct Elf64_Phdr)) ||
       /* Check that the number of entries is reasonable. */
       (image->elf_image.e_phnum < 0) ||
       (image->elf_image.e_phnum > 8) ||
       /* Check that the entry point is within the image. */
       (image->elf_image.e_entry < 0) ||
       (image->elf_image.e_entry >= image_size) ||
       /* Finally, check that the program header table is within the image. */
       (image->elf_image.e_phoff > image_size) ||
       ((image->elf_image.e_phoff +
         image->elf_image.e_phnum * sizeof(struct Elf64_Phdr)) > image_size )
      )
   {
    /* There is something wrong with the image. */
    while (1)
    {
     kprints("Kernel panic! Corrupt executable image.\n");
    }
    continue;
   }
   /* Now check the program header table. */
   {
    int                program_header_index;
    struct Elf64_Phdr* program_header = ((struct Elf64_Phdr*)
                                         (((char*) &(image->elf_image)) +
                                          image->elf_image.e_phoff));
    unsigned long      memory_footprint_size = 0;
    for (program_header_index = 0;
         program_header_index < image->elf_image.e_phnum;
         program_header_index++)
    {
     /* First sanity check the entry. */
     if (
         /* Check that the segment is a type we can handle. */
         (program_header[program_header_index].p_type < 0) ||
         (!((program_header[program_header_index].p_type == PT_NULL) ||
            (program_header[program_header_index].p_type == PT_LOAD) ||
            (program_header[program_header_index].p_type == PT_PHDR))) ||
         /* Look more carefully into loadable segments. */
         ((program_header[program_header_index].p_type == PT_LOAD) &&
           /* Check if any flags that we can not handle is set. */
          (((program_header[program_header_index].p_flags & ~7) != 0) ||
           /* Check if sizes and offsets look sane. */
           (program_header[program_header_index].p_offset < 0) ||
           (program_header[program_header_index].p_vaddr < 0) ||
           (program_header[program_header_index].p_filesz < 0) ||
           (program_header[program_header_index].p_memsz < 0) ||
          /* Check if the segment has an odd size. We require the
             segment size to be an even multiple of 8. */
           (0 != (program_header[program_header_index].p_memsz&7)) ||
           (0 != (program_header[program_header_index].p_filesz&7)) ||
           /* Check if the segment goes beyond the image. */
           ((program_header[program_header_index].p_offset +
             program_header[program_header_index].p_filesz) > image_size)))
        )
     {
      while (1)
      {
       kprints("Kernel panic! Corrupt segment.\n");
      }
     }
     /* Check that all PT_LOAD segments are contiguous starting from
        address 0. Also, calculate the memory footprint of the image. */
     if (program_header[program_header_index].p_type == PT_LOAD)
     {
      if (program_header[program_header_index].p_vaddr !=
          memory_footprint_size)
      {
       while (1)
       {
        kprints("Kernel panic! Executable image has illegal memory layout.\n");
       }
      }
      memory_footprint_size += program_header[program_header_index].p_memsz;
     }
    }
    executable_table[executable_table_size].memory_footprint_size =
     memory_footprint_size;
   }
   executable_table[executable_table_size].elf_image = &(image->elf_image);
   executable_table_size += 1;
   kprints("Found an executable image.\n");
   if (executable_table_size >= MAX_NUMBER_OF_PROCESSES)
   {
    while (1)
    {
     kprints("Kernel panic! Too many executable images found.\n");
    }
   }
  }
 }
 /* Check that actually some executable files are found. Also check that the
    thread structure is of the right size. The assembly code will break if it
    is not. Finally, initialize memory protection. You will implement memory
    protection in task A4. */
 if ((0 >= executable_table_size) ||
     (1024 != sizeof(union thread)))
 {
  while (1)
  {
   kprints("Kernel panic! Can not boot.\n");
  }
 }
 initialize_memory_protection();
 initialize_ports();
 initialize_thread_synchronization();
 /* All sub-systems are now initialized. Kernel areas can now get the right
    memory protection. */
 {
  /* Use the kernel's ELF header. */
  struct Elf32_Phdr* program_header = ((struct Elf32_Phdr*)
                                       (((char*) (0x00100000)) +
                                        ((struct Elf32_Ehdr*)0x00100000)->
                                          e_phoff));
  /* Traverse the program header. */
  short              number_of_program_header_entries =
                      ((struct Elf32_Ehdr*)0x00100000)->e_phnum;
  int                i;
  for(i=0; i<number_of_program_header_entries; i++)
  {
   if (PT_LOAD == program_header[i].p_type)
   {
    /* Set protection on each segment. */
    update_memory_protection(kernel_page_table_root,
                             program_header[i].p_vaddr,
                             program_header[i].p_memsz,
                             (program_header[i].p_flags&7) | PF_KERNEL);
   }
  }
 }
 /* Start running the first program in the executable table. */
 /* Use the ELF program header table and copy the right portions of the
    image to memory. This is done by prepare_process. */
 {
  struct prepare_process_return_value prepare_process_ret_val =
   prepare_process(executable_table[0].elf_image,
                   0,
                   executable_table[0].memory_footprint_size);
  if (0 == prepare_process_ret_val.first_instruction_address)
  {
   while (1)
   {
    kprints("Kernel panic! Can not start process 0!\n");
   }
  }
  /* Start executable program 0 as process 0. At this point, there are no
     processes so we can just grab entry 0 and use it. */
  process_table[0].parent=-1;    /* We put -1 to indicate that there is no
                                    parent process. */
  process_table[0].threads=1;
  /*  all processes should start with an allocated port with id zero */
  if (-1 == allocate_port(0,0))
  {
   while(1)
   {
    kprints("Kernel panic! Can not initialize the IPC system!\n");
   }
  }
  /* Set the page table address. */
  process_table[0].page_table_root =
   prepare_process_ret_val.page_table_address;
  cpu_private_data.page_table_root =
   prepare_process_ret_val.page_table_address;
  /* We need a thread. We just take the first one as no threads are running or
     have been allocated at this point. */
  thread_table[0].data.owner=0;  /* 0 is the index of the first process. */
  /* We reset all flags and enable interrupts */
  thread_table[0].data.registers.integer_registers.rflags=0x200;
  /* And set the start address. */
  thread_table[0].data.registers.integer_registers.rip =
   prepare_process_ret_val.first_instruction_address;
  /* Finally we set the current thread. */
  cpu_private_data.thread_index = 0;
 }
 /* Set up the timer hardware to generate interrupts 200 times a second. */
 outb(0x43, 0x36);
 outb(0x40, 78);
 outb(0x40, 23);
 /* Set up the keyboard controller. */
 /* Empty the keyboard buffer. */
 {
  register unsigned char status_byte;
  do
  {
   status_byte=inb(0x64);
   if ((status_byte&3)==1)
   {
    inb(0x60);
   }
  } while((status_byte&0x3)!=0x0);
 }
 /* Change the command byte to enable interrupts. */
 outb(0x64, 0x20);
 {
  register unsigned char keyboard_controller_command_byte;
  {
   register unsigned char status_byte;
   do
   {
    status_byte=inb(0x64);
   } while((status_byte&3)!=1);
  }
  keyboard_controller_command_byte=inb(0x60);
  /* Enable keyboard interrupts. */
  keyboard_controller_command_byte|=1;
  kprints("Keyboard controller command byte:");
  kprinthex(keyboard_controller_command_byte);
  kprints("\n");
  outb(0x64, 0x60);
  outb(0x60, keyboard_controller_command_byte);
  /* Wait until command is done. */
  {
   register unsigned char status_byte;
   do
   {
    status_byte=inb(0x64);
   } while((status_byte&0x2)!=0x0);
  }
 }
 /* Now we set up the interrupt controller to allow timer and keyboard
    interrupts. */
 outb(0x20, 0x11);
 outb(0xA0, 0x11);
 outb(0x21, 0x20);
 outb(0xA1, 0x28);
 outb(0x21, 1<<2);
 outb(0xA1, 2);
 outb(0x21, 1);
 outb(0xA1, 1);
 outb(0x21, 0xfc);
 outb(0xA1, 0xff);
 clear_screen();
 kprints("\n\n\nThe kernel has booted!\n\n\n");
 /* Now go back to the assembly language code and let the process run. */
}
void interrupt_dispatcher (const unsigned long interrupt_number)
This function gets called from the interrupt handler and dispatches interrupts to interrupt handlers.
Parameters:
interrupt_number The number of the interrupt vector.
Definition at line 977 of file kernel.c.
References keyboard_interrupt_handler(), kprinthex(), kprints(), outb(), outw(), and timer_interrupt_handler().
{
 /* Select a handler based on interrupt source. */
 switch(interrupt_number)
 {
  case 32:
  {
   timer_interrupt_handler();
   break;
  }
  case 33:
  {
   keyboard_interrupt_handler();
   break;
  }
  case 39:
  {
   /* Spurious interrupt occurred. This could happen if we spend too long
      time with interrupts disabled. */
   break;
  }
  default:
  {
   kprints("Unknown interrupt. Vector:");
   kprinthex(interrupt_number);
   kprints("\n");
   while(1)
   {
    outw(0x8a00, 0x8a00);
    outw(0x8a00, 0x8ae0);
   }
  }
 }
 /* Acknowledge interrupt so that new interrupts can be sent to the CPU. */
 if (interrupt_number < 48)
 {
  if (interrupt_number >= 40)
  {
   outb(0xa0, 0x20);
  }
  outb(0x20, 0x20);
 }
}
static void keyboard_interrupt_handler (void) [inline, static]
Keyboard interrupt handler.
Definition at line 931 of file kernel.c.
References cpu_private_data, thread::data, inb(), context::integer_registers, keyboard_blocked_threads, KEYBOARD_BUFFER_SIZE, keyboard_scancode_buffer, keyboard_scancode_high_marker, keyboard_scancode_low_marker, thread::owner, CPU_private::page_table_root, process_table, context::rax, ready_queue, thread::registers, CPU_private::thread_index, thread_queue_dequeue(), thread_queue_enqueue(), thread_queue_is_empty(), and thread_table.
Referenced by interrupt_dispatcher().
{
 register unsigned char status_byte=inb(0x64);
 if ((status_byte&1)==1)
 {
  register unsigned char data=inb(0x60);
  /* Is a thread waiting for data? */
  if (thread_queue_is_empty(&keyboard_blocked_threads))
  {
   /* Store scan code in the buffer if there is space in the buffer. */
   register int buffer_size=keyboard_scancode_high_marker-
                            keyboard_scancode_low_marker;
   if (buffer_size<KEYBOARD_BUFFER_SIZE)
   {
    keyboard_scancode_buffer
     [(keyboard_scancode_high_marker++)&(KEYBOARD_BUFFER_SIZE-1)]=data;
   }
  }
  else
  {
   /* Let the first blocked thread get the scan code. */
   register int blocked_thread_index=
    thread_queue_dequeue(&keyboard_blocked_threads);
   thread_table[blocked_thread_index].data.registers.integer_registers.rax=
    data;
   /* Let the woken thread run if the CPU is not running any thread. */
   if (-1 == cpu_private_data.thread_index)
   {
    cpu_private_data.thread_index = blocked_thread_index;
    cpu_private_data.page_table_root =
     process_table[thread_table[blocked_thread_index].data.owner].
      page_table_root;
   }
   else
   {
    thread_queue_enqueue(&ready_queue, blocked_thread_index);
   }
  }
 }
}
static struct prepare_process_return_value prepare_process (const struct Elf64_Ehdr * elf_image, const unsigned int process, unsigned long memory_footprint_size) [static, read]
Copies an ELF image to memory and prepares a process.
prepare_process does some checks to avoid that corrupt images gets copied to memory. However, the checks are not as thorough as the check in initialize.
Returns:
A prepare_process_return_value struct holding the first address of the process image and an address to the page table for the process.
Parameters:
elf_image Points to the ELF image to copy.
process The index of the process that is to be created.
memory_footprint_size Holds the maximum amount of memory, in bytes, the image is allowed to use.
Definition at line 84 of file kernel.c.
References ALLOCATE_FLAG_KERNEL, prepare_process_return_value::first_instruction_address, kalloc(), kernel_page_table_root, kprints(), Elf64_Phdr::p_filesz, Elf64_Phdr::p_flags, Elf64_Phdr::p_memsz, Elf64_Phdr::p_offset, Elf64_Phdr::p_vaddr, prepare_process_return_value::page_table_address, PT_LOAD, and update_memory_protection().
Referenced by initialize().
{
 /* Get the address of the program header table. */
 int                program_header_index;
 struct Elf64_Phdr* program_header = ((struct Elf64_Phdr*)
                                       (((char*) (elf_image)) +
                                        elf_image->e_phoff));
 unsigned long      used_memory = 0;
 /* Allocate memory for the page table and for the process' memory. All of
    this is allocated in a single memory block. The memory block is set up so
    that it cannot be de-allocated via kfree. */
 long               address_to_memory_block =
  kalloc(memory_footprint_size+19*4*1024, process, ALLOCATE_FLAG_KERNEL);
 struct prepare_process_return_value ret_val = {0, 0};
 /* First check that we have enough memory. */
 if (0 >= address_to_memory_block)
 {
  /* No, we don't. */
  return ret_val;
 }
 ret_val.page_table_address = address_to_memory_block;
 {
  /* Create a page table for the process. */
  unsigned long* dst = (unsigned long*) address_to_memory_block;
  unsigned long* src = (unsigned long*) (kernel_page_table_root + 3*4*1024);
  register int i;
  /* Clear the first frames. */
  for(i=0; i<3*4*1024/8; i++)
  {
   *dst = 0;
  }
  /* Build the pml4 table. */
  dst = (unsigned long*) (address_to_memory_block);
  *dst = (address_to_memory_block+4096) | 7;
  /* Build the pdp table. */
  dst = (unsigned long*) (address_to_memory_block+4096);
  *dst = (address_to_memory_block+2*4096) | 7;
  /* Build the pd table. */
  dst = (unsigned long*) (address_to_memory_block+2*4096);
  for(i=0; i<16; i++)
  {
   *dst++ = (address_to_memory_block+(3+i)*4096) | 7;
  }
  /* Copy the rest of the kernel page table. */
  dst = (unsigned long*) (address_to_memory_block + 3*4*1024);
  for(i=0; i<(16*1024*4/8); i++)
  {
   *dst++ = *src++;
  }
 }
 /* Update the start of the block to be after the page table. */
 address_to_memory_block += 19*4*1024;
 /* Scan through the program header table and copy all PT_LOAD segments to
    memory. Perform checks at the same time.*/
 for (program_header_index = 0;
      program_header_index < elf_image->e_phnum;
      program_header_index++)
 {
  if (PT_LOAD == program_header[program_header_index].p_type)
  {
   /* Calculate destination adress. */
   unsigned long* dst = (unsigned long *) (address_to_memory_block +
                                           used_memory);
   /* Check for odd things. */
   if (
       /* Check if the segment is contiguous */
       (used_memory != program_header[program_header_index].p_vaddr) ||
       /* Check if the segmen fits in memory. */
       (used_memory + program_header[program_header_index].p_memsz >
        memory_footprint_size) ||
       /* Check if the segment has an odd size. We require the segment
          size to be an even multiple of 8. */
       (0 != (program_header[program_header_index].p_memsz&7)) ||
       (0 != (program_header[program_header_index].p_filesz&7)))
   {
    /* Something went wrong. Panic. */
    while(1)
    {
     kprints(
"Kernel panic: Trying to create a process out of a corrupt executable image!");
    }
   }
   /* First copy p_filesz from the image to memory. */
   {
    /* Calculate the source address. */
    unsigned long* src = (unsigned long *) (((char*) elf_image)+
     program_header[program_header_index].p_offset);
    unsigned long count = program_header[program_header_index].p_filesz/8;
    for(; count>0; count--)
    {
     *dst++=*src++;
    }
   }
   /* Then write p_memsz-p_filesz bytes of zeros. This to pad the segment. */
   {
    unsigned long count = (program_header[program_header_index].p_memsz-
                           program_header[program_header_index].p_filesz)/8;
    for(; count>0; count--)
    {
     *dst++=0;
    }
   }
   /* Set the permission bits on the loaded segment. */
   update_memory_protection(ret_val.page_table_address,
                            program_header[program_header_index].p_vaddr+
                             address_to_memory_block,
                            program_header[program_header_index].p_memsz,
                            program_header[program_header_index].p_flags&7);
   /* Finally update the amount of used memory. */
   used_memory += program_header[program_header_index].p_memsz;
  }
 }
 /* Find out the address to the first instruction to be executed. */
 ret_val.first_instruction_address = address_to_memory_block +
                                     elf_image->e_entry;
 return ret_val;
}
Variable Documentation
const char* const ELF_images_end
The address of the first byte after the end of the last ELF image.
This variable is used for sanity checking.
Definition at line 37 of file kernel.c.
Referenced by initialize().
struct executable_image* const ELF_images_start
The first executable image in the linked list of executable images.
Definition at line 35 of file kernel.c.
struct executable executable_table[MAX_NUMBER_OF_PROCESSES] [static]
Array holding descriptions of all executable programs.
Definition at line 26 of file kernel.c.
Referenced by initialize().
int executable_table_size = 0 [static]
The number of executable programs in the executable_table.
Definition at line 31 of file kernel.c.
Referenced by initialize().
struct thread_queue keyboard_blocked_threads
List of threads blocked waiting for scan codes.
Definition at line 64 of file kernel.c.
Referenced by initialize(), and keyboard_interrupt_handler().
unsigned char keyboard_scancode_buffer[KEYBOARD_BUFFER_SIZE] [static]
Buffer which holds the keyboard scan codes coming from the keyboard interrupt handler.
Definition at line 53 of file kernel.c.
Referenced by keyboard_interrupt_handler().
int keyboard_scancode_high_marker = 0 [static]
High water mark for the scan code buffer.
Definition at line 61 of file kernel.c.
Referenced by keyboard_interrupt_handler().
int keyboard_scancode_low_marker = 0 [static]
Low water mark for the scan code buffer.
Definition at line 57 of file kernel.c.
Referenced by keyboard_interrupt_handler().
struct process process_table[MAX_NUMBER_OF_PROCESSES]
Array holding all processes in the system.
Definition at line 20 of file kernel.c.
Referenced by initialize(), and keyboard_interrupt_handler().
struct thread_queue ready_queue
The ready queue.
Note:
Linked lists are terminated with a thread with a next index of -1.
Definition at line 23 of file kernel.c.
Referenced by initialize(), and keyboard_interrupt_handler().
long system_time = 0
This variable holds the current system time.
The system time is the number of clock ticks since system start. There are 200 clock ticks per second.
Definition at line 45 of file kernel.c.
union thread thread_table[MAX_NUMBER_OF_THREADS]
Array holding all threads in the systems.
Definition at line 17 of file kernel.c.
Referenced by allocate_thread(), initialize(), keyboard_interrupt_handler(), thread_queue_dequeue(), and thread_queue_enqueue().
int timer_queue_head = -1
The index, into thread_table, of the head of the timer queue.
The timer queue is a list of threads blocked waiting for the system clock to reach a certain time. This variable is set to -1 if there are no threads in the timer queue.
Definition at line 41 of file kernel.c.