02333 Task 7: src/kernel/kernel.h File Reference
src/kernel/kernel.h File Reference
This file holds kernel wide macros and declarations.
#include <sysdefines.h>
Data Structures
struct context
Defines an execution context.
union thread
Defines a thread.
struct process
Defines a process.
struct Elf64_Ehdr
Defines an ELF64 file header.
struct Elf32_Ehdr
Defines an ELF32 file header.
struct Elf64_Phdr
Defines an entry in the ELF program header table.
struct Elf32_Phdr
Defines an entry in the ELF32 program header table.
struct executable
Defines an executable program.
struct executable_image
Defines an executable image embedded into the kernel image.
struct CPU_private
Defines the structure pointed to by the kernel GS_BASE.
struct screen_position
struct screen
Defines
#define SYSCALL_ARGUMENTS
Macro used in the system call switch to access the arguments to the system call.
#define KERNEL_VERSION (0x0000000100000000)
Kernel version number.
#define MAX_NUMBER_OF_PROCESSES (16)
Size of the process_table.
#define MAX_NUMBER_OF_THREADS (256)
Size of the thread_table.
#define EI_MAG0 0
The first four bytes in an ELF image is 0x7f 'E' 'L' 'F'.
#define EI_MAG1 1
#define EI_MAG2 2
#define EI_MAG3 3
#define EI_CLASS 4
The specific ELF image class.
#define EI_DATA 5
Describes if the image is big- or little- endian.
#define EI_VERSION 6
The version of the ELF specification the image adheres to.
#define EI_OSABI 7
Type of OS the image can be run on.
#define EI_ABIVERSION 8
Version of the ABI used.
#define EI_PAD 9
First unused byte in the identification array.
#define EI_NIDENT 16
Number of entries in the identification array.
#define PT_NULL 0
The entry is not used.
#define PT_LOAD 1
The segment can be loaded into memory.
#define PT_PHDR 6
The segment only hold a program header table.
#define PF_X 0x1
Segment can be executed.
#define PF_W 0x2
Segment can be written.
#define PF_R 0x4
Segment can be read.
#define PF_MASKPERM 0x0000FFFF
Used to mask the permission bits.
Functions
void initialize (void)
This fuction initializes the kernel after the assembly code portion has set the system and the CPU up.
void system_call_handler (void)
This function gets called from the syscall handler and responds to the system calls.
void interrupt_dispatcher (const unsigned long interrupt_number)
This function gets called from the interrupt handler and dispatches interrupts to interrupt handlers.
void timer_interrupt_handler (void)
This function gets called from the interrupt dispatcher and manages timer interrupts.
void kprints (const char *const string)
Outputs a string to the bochs console.
void kprinthex (const register long value)
Prints a long formatted as a hexadecimal number to the bochs console.
void clear_screen (void)
Clears the VGA buffer which is used in task 7.
static void outb (const short port_number, const char output_value)
Wrapper for a byte out instruction.
static void outw (const short port_number, const short output_value)
Wrapper for a word out instruction.
static char inb (const short port_number)
Wrapper for a byte in instruction.
static short inw (const short port_number)
Wrapper for a word in instruction.
Variables
struct screen *const screen_pointer
Points to the VGA screen.
union thread thread_table [MAX_NUMBER_OF_THREADS]
Array holding all threads in the systems.
struct process process_table [MAX_NUMBER_OF_PROCESSES]
Array holding all processes in the system.
struct executable_image *const ELF_images_start
The first executable image in the linked list of executable images.
const char *const ELF_images_end
The address of the first byte after the end of the last ELF image.
struct thread_queue ready_queue
The ready queue.
int timer_queue_head
The index, into thread_table, of the head of the timer queue.
long system_time
This variable holds the current system time.
struct CPU_private cpu_private_data
Holds data private to the CPU.
Detailed Description
This file holds kernel wide macros and declarations.
Definition in file kernel.h.
Define Documentation
#define EI_ABIVERSION 8
Version of the ABI used.
Definition at line 117 of file kernel.h.
#define EI_CLASS 4
The specific ELF image class.
Definition at line 111 of file kernel.h.
Referenced by initialize().
#define EI_DATA 5
Describes if the image is big- or little- endian.
Definition at line 112 of file kernel.h.
Referenced by initialize().
#define EI_MAG0 0
The first four bytes in an ELF image is 0x7f 'E' 'L' 'F'.
Definition at line 106 of file kernel.h.
Referenced by initialize().
#define EI_MAG1 1
Definition at line 108 of file kernel.h.
Referenced by initialize().
#define EI_MAG2 2
Definition at line 109 of file kernel.h.
Referenced by initialize().
#define EI_MAG3 3
Definition at line 110 of file kernel.h.
Referenced by initialize().
#define EI_NIDENT 16
Number of entries in the identification array.
Definition at line 120 of file kernel.h.
#define EI_OSABI 7
Type of OS the image can be run on.
Definition at line 116 of file kernel.h.
#define EI_PAD 9
First unused byte in the identification array.
Definition at line 118 of file kernel.h.
#define EI_VERSION 6
The version of the ELF specification the image adheres to.
Definition at line 114 of file kernel.h.
Referenced by initialize().
#define KERNEL_VERSION (0x0000000100000000)
Kernel version number.
Definition at line 22 of file kernel.h.
#define MAX_NUMBER_OF_PROCESSES (16)
Size of the process_table.
Definition at line 25 of file kernel.h.
Referenced by initialize().
#define MAX_NUMBER_OF_THREADS (256)
Size of the thread_table.
Definition at line 27 of file kernel.h.
Referenced by allocate_thread(), and initialize().
#define PF_MASKPERM 0x0000FFFF
Used to mask the permission bits.
Definition at line 230 of file kernel.h.
#define PF_R 0x4
Segment can be read.
Definition at line 229 of file kernel.h.
#define PF_W 0x2
Segment can be written.
Definition at line 228 of file kernel.h.
#define PF_X 0x1
Segment can be executed.
Definition at line 227 of file kernel.h.
#define PT_LOAD 1
The segment can be loaded into memory.
Definition at line 224 of file kernel.h.
Referenced by initialize(), and prepare_process().
#define PT_NULL 0
The entry is not used.
Definition at line 223 of file kernel.h.
Referenced by initialize().
#define PT_PHDR 6
The segment only hold a program header table.
Definition at line 225 of file kernel.h.
Referenced by initialize().
#define SYSCALL_ARGUMENTS
Value:
(thread_table[cpu_private_data.thread_index].\
                           data.registers.integer_registers)
Macro used in the system call switch to access the arguments to the system call.
Definition at line 17 of file kernel.h.
Function Documentation
void clear_screen (void)
Clears the VGA buffer which is used in task 7.
Definition at line 7 of file video.c.
References screen_position::character, MAX_COLS, MAX_ROWS, screen::positions, and screen_pointer.
Referenced by initialize().
{
 register int row, column;
 for(row=0; row<MAX_ROWS; row++)
 {
  for(column=0; column<MAX_COLS; column++)
  {
   screen_pointer->positions[row][column].character=' ';
  }
 }
}
static char inb (const short port_number) [inline, static]
Wrapper for a byte in instruction.
Definition at line 396 of file kernel.h.
Referenced by initialize(), and keyboard_interrupt_handler().
{
 char return_value;
 __asm volatile("inb %%dx,%%al" : "=a" (return_value) : "d" (port_number));
 return return_value;
}
void initialize (void)
This fuction initializes the kernel after the assembly code portion has set the system and the CPU up.
Definition at line 253 of file kernel.c.
References allocate_port(), clear_screen(), cpu_private_data, thread::data, Elf64_Ehdr::e_ehsize, Elf64_Ehdr::e_flags, Elf64_Ehdr::e_ident, Elf64_Ehdr::e_machine, Elf32_Ehdr::e_phoff, Elf64_Ehdr::e_type, Elf64_Ehdr::e_version, EI_CLASS, EI_DATA, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, EI_VERSION, executable::elf_image, executable_image::elf_image, ELF_images_end, executable_table, executable_table_size, first_available_memory_byte, prepare_process_return_value::first_instruction_address, page_frame::free_is_allowed, inb(), initialize_memory_protection(), initialize_ports(), initialize_thread_synchronization(), context::integer_registers, kernel_page_table_root, keyboard_blocked_threads, kprinthex(), kprints(), MAX_NUMBER_OF_FRAMES, MAX_NUMBER_OF_PROCESSES, MAX_NUMBER_OF_THREADS, executable::memory_footprint_size, memory_pages, memory_size, executable_image::next, outb(), page_frame::owner, thread::owner, Elf64_Phdr::p_filesz, Elf64_Phdr::p_flags, Elf64_Phdr::p_memsz, Elf64_Phdr::p_offset, Elf64_Phdr::p_type, Elf64_Phdr::p_vaddr, page_frame_table, prepare_process_return_value::page_table_address, CPU_private::page_table_root, process::page_table_root, process::parent, PF_KERNEL, prepare_process(), process_table, PT_LOAD, PT_NULL, PT_PHDR, ready_queue, thread::registers, context::rflags, context::rip, CPU_private::thread_index, thread_queue_init(), thread_table, process::threads, and update_memory_protection().
{
 register int i;
 /* Loop over all threads in the thread table and reset the owner. */
 for(i=0; i<MAX_NUMBER_OF_THREADS; i++)
 {
  thread_table[i].data.owner=-1; /* -1 is an illegal process_table index.
                                     We use that to show that the thread
                                     is dormant. */
 }
 /* Loop over all processes in the thread table and mark them as not
    executing. */
 for(i=0; i<MAX_NUMBER_OF_PROCESSES; i++)
 {
  process_table[i].threads=0;    /* No executing process has less than 1
                                    thread. */
 }
 /* Initialize the ready queue. */
 thread_queue_init(&ready_queue);
 /* Initialize the list of blocked threads waiting for the keyboard. */
 thread_queue_init(&keyboard_blocked_threads);
 /* Calculate the number of pages. */
 memory_pages = memory_size/(4*1024);
 {
  /* Calculate the number of frames occupied by the kernel and executable
     images. */
  const register int k=first_available_memory_byte/(4*1024);
  /* Mark the pages that are used by the kernel or executable images as taken
    by the kernel (-2 in the owner field). */
  for(i=0; i<k; i++)
  {
   page_frame_table[i].owner=-2;
   page_frame_table[i].free_is_allowed=0;
  }
  /* Loop over all the rest page frames and mark them as free (-1 in owner
     field). */
  for(i=k; i<memory_pages; i++)
  {
   page_frame_table[i].owner=-1;
   page_frame_table[i].free_is_allowed=1;
  }
  /* Mark any unusable pages as taken by the kernel. */
  for(i=memory_pages; i<MAX_NUMBER_OF_FRAMES; i++)
  {
   page_frame_table[i].owner=-2;
   page_frame_table[i].free_is_allowed=0;
  }
 }
 /* Go through the linked list of executable images and verify that they
    are correct. At the same time build the executable_table. */
 {
  const struct executable_image* image;
  for (image=ELF_images_start; 0!=image; image=image->next)
  {
   unsigned long      image_size;
   /* First calculate the size of the image. */
   if (0 != image->next)
   {
    image_size = ((char *) (image->next)) - ((char *) image) -1;
   }
   else
   {
    image_size = ((char *) ELF_images_end) - ((char *) image) - 1;
   }
   /* Check that the image is an ELF image and that it is of the
      right type. */
   if (
       /* EI_MAG0 - EI_MAG3 have to be 0x7f 'E' 'L' 'F'. */
       (image->elf_image.e_ident[EI_MAG0] != 0x7f) ||
       (image->elf_image.e_ident[EI_MAG1] != 'E') ||
       (image->elf_image.e_ident[EI_MAG2] != 'L') ||
       (image->elf_image.e_ident[EI_MAG3] != 'F') ||
       /* Check that the image is a 64-bit image. */
       (image->elf_image.e_ident[EI_CLASS] != 2) ||
       /* Check that the image is a little endian image. */
       (image->elf_image.e_ident[EI_DATA] != 1) ||
       /* And that the version of the image format is correct. */
       (image->elf_image.e_ident[EI_VERSION] != 1) ||
       /* NB: We do not check the ABI or ABI version. We really should
          but currently those fields are not set properly by the build
          tools. They are both set to zero which means: System V ABI,
          third edition. However, the ABI used is clearly not System V :-) */
       /* Check that the image is executable. */
       (image->elf_image.e_type != 2) ||
       /* Check that the image is executable on AMD64. */
       (image->elf_image.e_machine != 0x3e) ||
       /* Check that the object format is corrent. */
       (image->elf_image.e_version != 1) ||
       /* Check that the processor dependent flags are all reset. */
       (image->elf_image.e_flags != 0) ||
       /* Check that the length of t   he header is what we expect. */
       (image->elf_image.e_ehsize != sizeof(struct Elf64_Ehdr)) ||
       /* Check that the size of the program header table entry is what
          we expect. */
       (image->elf_image.e_phentsize != sizeof(struct Elf64_Phdr)) ||
       /* Check that the number of entries is reasonable. */
       (image->elf_image.e_phnum < 0) ||
       (image->elf_image.e_phnum > 8) ||
       /* Check that the entry point is within the image. */
       (image->elf_image.e_entry < 0) ||
       (image->elf_image.e_entry >= image_size) ||
       /* Finally, check that the program header table is within the image. */
       (image->elf_image.e_phoff > image_size) ||
       ((image->elf_image.e_phoff +
         image->elf_image.e_phnum * sizeof(struct Elf64_Phdr)) > image_size )
      )
   {
    /* There is something wrong with the image. */
    while (1)
    {
     kprints("Kernel panic! Corrupt executable image.\n");
    }
    continue;
   }
   /* Now check the program header table. */
   {
    int                program_header_index;
    struct Elf64_Phdr* program_header = ((struct Elf64_Phdr*)
                                         (((char*) &(image->elf_image)) +
                                          image->elf_image.e_phoff));
    unsigned long      memory_footprint_size = 0;
    for (program_header_index = 0;
         program_header_index < image->elf_image.e_phnum;
         program_header_index++)
    {
     /* First sanity check the entry. */
     if (
         /* Check that the segment is a type we can handle. */
         (program_header[program_header_index].p_type < 0) ||
         (!((program_header[program_header_index].p_type == PT_NULL) ||
            (program_header[program_header_index].p_type == PT_LOAD) ||
            (program_header[program_header_index].p_type == PT_PHDR))) ||
         /* Look more carefully into loadable segments. */
         ((program_header[program_header_index].p_type == PT_LOAD) &&
           /* Check if any flags that we can not handle is set. */
          (((program_header[program_header_index].p_flags & ~7) != 0) ||
           /* Check if sizes and offsets look sane. */
           (program_header[program_header_index].p_offset < 0) ||
           (program_header[program_header_index].p_vaddr < 0) ||
           (program_header[program_header_index].p_filesz < 0) ||
           (program_header[program_header_index].p_memsz < 0) ||
          /* Check if the segment has an odd size. We require the
             segment size to be an even multiple of 8. */
           (0 != (program_header[program_header_index].p_memsz&7)) ||
           (0 != (program_header[program_header_index].p_filesz&7)) ||
           /* Check if the segment goes beyond the image. */
           ((program_header[program_header_index].p_offset +
             program_header[program_header_index].p_filesz) > image_size)))
        )
     {
      while (1)
      {
       kprints("Kernel panic! Corrupt segment.\n");
      }
     }
     /* Check that all PT_LOAD segments are contiguous starting from
        address 0. Also, calculate the memory footprint of the image. */
     if (program_header[program_header_index].p_type == PT_LOAD)
     {
      if (program_header[program_header_index].p_vaddr !=
          memory_footprint_size)
      {
       while (1)
       {
        kprints("Kernel panic! Executable image has illegal memory layout.\n");
       }
      }
      memory_footprint_size += program_header[program_header_index].p_memsz;
     }
    }
    executable_table[executable_table_size].memory_footprint_size =
     memory_footprint_size;
   }
   executable_table[executable_table_size].elf_image = &(image->elf_image);
   executable_table_size += 1;
   kprints("Found an executable image.\n");
   if (executable_table_size >= MAX_NUMBER_OF_PROCESSES)
   {
    while (1)
    {
     kprints("Kernel panic! Too many executable images found.\n");
    }
   }
  }
 }
 /* Check that actually some executable files are found. Also check that the
    thread structure is of the right size. The assembly code will break if it
    is not. Finally, initialize memory protection. You will implement memory
    protection in task A4. */
 if ((0 >= executable_table_size) ||
     (1024 != sizeof(union thread)))
 {
  while (1)
  {
   kprints("Kernel panic! Can not boot.\n");
  }
 }
 initialize_memory_protection();
 initialize_ports();
 initialize_thread_synchronization();
 /* All sub-systems are now initialized. Kernel areas can now get the right
    memory protection. */
 {
  /* Use the kernel's ELF header. */
  struct Elf32_Phdr* program_header = ((struct Elf32_Phdr*)
                                       (((char*) (0x00100000)) +
                                        ((struct Elf32_Ehdr*)0x00100000)->
                                          e_phoff));
  /* Traverse the program header. */
  short              number_of_program_header_entries =
                      ((struct Elf32_Ehdr*)0x00100000)->e_phnum;
  int                i;
  for(i=0; i<number_of_program_header_entries; i++)
  {
   if (PT_LOAD == program_header[i].p_type)
   {
    /* Set protection on each segment. */
    update_memory_protection(kernel_page_table_root,
                             program_header[i].p_vaddr,
                             program_header[i].p_memsz,
                             (program_header[i].p_flags&7) | PF_KERNEL);
   }
  }
 }
 /* Start running the first program in the executable table. */
 /* Use the ELF program header table and copy the right portions of the
    image to memory. This is done by prepare_process. */
 {
  struct prepare_process_return_value prepare_process_ret_val =
   prepare_process(executable_table[0].elf_image,
                   0,
                   executable_table[0].memory_footprint_size);
  if (0 == prepare_process_ret_val.first_instruction_address)
  {
   while (1)
   {
    kprints("Kernel panic! Can not start process 0!\n");
   }
  }
  /* Start executable program 0 as process 0. At this point, there are no
     processes so we can just grab entry 0 and use it. */
  process_table[0].parent=-1;    /* We put -1 to indicate that there is no
                                    parent process. */
  process_table[0].threads=1;
  /*  all processes should start with an allocated port with id zero */
  if (-1 == allocate_port(0,0))
  {
   while(1)
   {
    kprints("Kernel panic! Can not initialize the IPC system!\n");
   }
  }
  /* Set the page table address. */
  process_table[0].page_table_root =
   prepare_process_ret_val.page_table_address;
  cpu_private_data.page_table_root =
   prepare_process_ret_val.page_table_address;
  /* We need a thread. We just take the first one as no threads are running or
     have been allocated at this point. */
  thread_table[0].data.owner=0;  /* 0 is the index of the first process. */
  /* We reset all flags and enable interrupts */
  thread_table[0].data.registers.integer_registers.rflags=0x200;
  /* And set the start address. */
  thread_table[0].data.registers.integer_registers.rip =
   prepare_process_ret_val.first_instruction_address;
  /* Finally we set the current thread. */
  cpu_private_data.thread_index = 0;
 }
 /* Set up the timer hardware to generate interrupts 200 times a second. */
 outb(0x43, 0x36);
 outb(0x40, 78);
 outb(0x40, 23);
 /* Set up the keyboard controller. */
 /* Empty the keyboard buffer. */
 {
  register unsigned char status_byte;
  do
  {
   status_byte=inb(0x64);
   if ((status_byte&3)==1)
   {
    inb(0x60);
   }
  } while((status_byte&0x3)!=0x0);
 }
 /* Change the command byte to enable interrupts. */
 outb(0x64, 0x20);
 {
  register unsigned char keyboard_controller_command_byte;
  {
   register unsigned char status_byte;
   do
   {
    status_byte=inb(0x64);
   } while((status_byte&3)!=1);
  }
  keyboard_controller_command_byte=inb(0x60);
  /* Enable keyboard interrupts. */
  keyboard_controller_command_byte|=1;
  kprints("Keyboard controller command byte:");
  kprinthex(keyboard_controller_command_byte);
  kprints("\n");
  outb(0x64, 0x60);
  outb(0x60, keyboard_controller_command_byte);
  /* Wait until command is done. */
  {
   register unsigned char status_byte;
   do
   {
    status_byte=inb(0x64);
   } while((status_byte&0x2)!=0x0);
  }
 }
 /* Now we set up the interrupt controller to allow timer and keyboard
    interrupts. */
 outb(0x20, 0x11);
 outb(0xA0, 0x11);
 outb(0x21, 0x20);
 outb(0xA1, 0x28);
 outb(0x21, 1<<2);
 outb(0xA1, 2);
 outb(0x21, 1);
 outb(0xA1, 1);
 outb(0x21, 0xfc);
 outb(0xA1, 0xff);
 clear_screen();
 kprints("\n\n\nThe kernel has booted!\n\n\n");
 /* Now go back to the assembly language code and let the process run. */
}
void interrupt_dispatcher (const unsigned long interrupt_number)
This function gets called from the interrupt handler and dispatches interrupts to interrupt handlers.
Parameters:
interrupt_number The number of the interrupt vector.
Definition at line 977 of file kernel.c.
References keyboard_interrupt_handler(), kprinthex(), kprints(), outb(), outw(), and timer_interrupt_handler().
{
 /* Select a handler based on interrupt source. */
 switch(interrupt_number)
 {
  case 32:
  {
   timer_interrupt_handler();
   break;
  }
  case 33:
  {
   keyboard_interrupt_handler();
   break;
  }
  case 39:
  {
   /* Spurious interrupt occurred. This could happen if we spend too long
      time with interrupts disabled. */
   break;
  }
  default:
  {
   kprints("Unknown interrupt. Vector:");
   kprinthex(interrupt_number);
   kprints("\n");
   while(1)
   {
    outw(0x8a00, 0x8a00);
    outw(0x8a00, 0x8ae0);
   }
  }
 }
 /* Acknowledge interrupt so that new interrupts can be sent to the CPU. */
 if (interrupt_number < 48)
 {
  if (interrupt_number >= 40)
  {
   outb(0xa0, 0x20);
  }
  outb(0x20, 0x20);
 }
}
static short inw (const short port_number) [inline, static]
Wrapper for a word in instruction.
Definition at line 405 of file kernel.h.
{
 short return_value;
 __asm volatile("inw %%dx,%%ax" : "=a" (return_value) : "d" (port_number));
 return return_value;
}
void kprinthex (const register long value)
Prints a long formatted as a hexadecimal number to the bochs console.
Parameters:
value The value to be written
Definition at line 42 of file video.c.
References outb().
Referenced by initialize(), and interrupt_dispatcher().
{
 const static char hex_helper[16]="0123456789abcdef";
 register int      i;
 /* Print each character of the hexadecimal number. This is a very inefficient
    way of printing hexadecimal numbers. It is, however, very compact in terms
    of the number of source code lines. */
 for(i=15; i>=0; i--)
 {
  outb(0xe9, hex_helper[(value>>(i*4))&15]);
 }
}
void kprints (const char *const string)
Outputs a string to the bochs console.
Parameters:
string Points to a null terminated string
Definition at line 23 of file video.c.
References outb().
Referenced by initialize(), interrupt_dispatcher(), and prepare_process().
{
 /* Loop until we have found the null character. */
 while(1)
 {
  register const char curr = *string++;
  if (curr)
  {
   outb(0xe9, curr);
  }
  else
  {
   return;
  }
 }
}
static void outb (const short port_number, const char output_value) [inline, static]
Wrapper for a byte out instruction.
Definition at line 382 of file kernel.h.
Referenced by initialize(), interrupt_dispatcher(), kprinthex(), and kprints().
{
 __asm volatile("outb %%al,%%dx" : : "d" (port_number), "a" (output_value));
}
static void outw (const short port_number, const short output_value) [inline, static]
Wrapper for a word out instruction.
Definition at line 389 of file kernel.h.
{
 __asm volatile("outw %%ax,%%dx" : : "d" (port_number), "a" (output_value));
}
void system_call_handler (void)
This function gets called from the syscall handler and responds to the system calls.
void timer_interrupt_handler (void)
This function gets called from the interrupt dispatcher and manages timer interrupts.
Referenced by interrupt_dispatcher().
Variable Documentation
struct CPU_private cpu_private_data
Holds data private to the CPU.
Referenced by cleanup_process(), initialize(), and keyboard_interrupt_handler().
const char* const ELF_images_end
The address of the first byte after the end of the last ELF image.
This variable is used for sanity checking.
Definition at line 37 of file kernel.c.
Referenced by initialize().
struct executable_image* const ELF_images_start
The first executable image in the linked list of executable images.
Definition at line 35 of file kernel.c.
struct process process_table[MAX_NUMBER_OF_PROCESSES]
Array holding all processes in the system.
Definition at line 20 of file kernel.c.
Referenced by initialize(), and keyboard_interrupt_handler().
struct thread_queue ready_queue
The ready queue.
Note:
Linked lists are terminated with a thread with a next index of -1.
Definition at line 23 of file kernel.c.
Referenced by initialize(), and keyboard_interrupt_handler().
struct screen* const screen_pointer
Points to the VGA screen.
Definition at line 4 of file video.c.
Referenced by clear_screen().
long system_time
This variable holds the current system time.
The system time is the number of clock ticks since system start. There are 200 clock ticks per second.
Definition at line 45 of file kernel.c.
union thread thread_table[MAX_NUMBER_OF_THREADS]
Array holding all threads in the systems.
Definition at line 17 of file kernel.c.
Referenced by allocate_thread(), initialize(), keyboard_interrupt_handler(), thread_queue_dequeue(), and thread_queue_enqueue().
int timer_queue_head
The index, into thread_table, of the head of the timer queue.
The timer queue is a list of threads blocked waiting for the system clock to reach a certain time. This variable is set to -1 if there are no threads in the timer queue.
Definition at line 41 of file kernel.c.