02333 Task 7: src/kernel/sync.c File Reference
src/kernel/sync.c File Reference
Holds the implementation of the synchronization sub-system.
#include "kernel.h"
#include "sync.h"
Functions
void initialize_ports (void)
Initializes the port table.
int allocate_port (const unsigned long id, const int new_owner)
Allocates and initializes one port from the port table.
int find_port (const unsigned long id, const int owner)
Find a port with identity if owned by process owner.
void initialize_thread_synchronization (void)
Initializes the thread synchronization sub-system.
Variables
struct port port_table [MAX_NUMBER_OF_PORTS]
Array holding information all ports.
Detailed Description
Holds the implementation of the synchronization sub-system.
Definition in file sync.c.
Function Documentation
int allocate_port (const unsigned long id, const int new_owner)
Allocates and initializes one port from the port table.
Returns:
an index into the port_table if a port could be allocated or -1 if no ports are available.
Parameters:
id Identity number of the port after allocation.
new_owner Id of the process becoming the new owner of the port after allocation.
Definition at line 26 of file sync.c.
References port::id, MAX_NUMBER_OF_PORTS, port::owner, port_table, port::receiver, port::sender_queue, and thread_queue_init().
Referenced by initialize().
{
 register int i;
 register int first_available=-1;
 /* Loop over all ports to see if the port has already been allocated. */
 for(i=0; i<MAX_NUMBER_OF_PORTS; i++)
 {
  /* We keep track of the first available port. This way we do not
     have to scan the table twice. */
  if ((-1 == port_table[i].owner) &&
      (-1 == first_available))
  {
   first_available=i;
  }
  /* Check if the port entry match the one we want to create. */
  if ((new_owner == port_table[i].owner) &&
      (id == port_table[i].id))
  {
   return -1;
  }
 }
 if (-1 != first_available)
 {
  /* Set the new owner and new identity. */
  port_table[first_available].owner=new_owner;
  port_table[first_available].id=id;
  /* Initially, the sender queue is  empty and there are no receiving thread. */
  port_table[first_available].receiver=-1;
  thread_queue_init(&port_table[first_available].sender_queue);
  return first_available;
 }
 /* Return -1 if we ran out of ports. */
 return -1;
}
int find_port (const unsigned long id, const int owner)
Find a port with identity if owned by process owner.
Returns:
the index into port_table of the port if a matching port is found. Returns -1 otherwise.
Parameters:
id Identity number of the port that we want to find.
owner Id of the owning process of the port that we want to find.
Definition at line 68 of file sync.c.
References MAX_NUMBER_OF_PORTS, and port_table.
{
 register int i;
 /* Loop over all ports in the table. */
 for(i=0; i<MAX_NUMBER_OF_PORTS; i++)
 {
  /* Return as soon as we find a match. */
  if ((owner == port_table[i].owner) &&
      (id == port_table[i].id))
  {
   return i;
  }
 }
 return -1;
}
void initialize_ports (void)
Initializes the port table.
Definition at line 13 of file sync.c.
References MAX_NUMBER_OF_PORTS, port::owner, and port_table.
Referenced by initialize().
{
 register int i;
 /* Loop over all ports in the table and set the owner to -1 indicating a
    free port. */
 for(i=0; i<MAX_NUMBER_OF_PORTS; i++)
 {
  port_table[i].owner=-1;
 }
}
void initialize_thread_synchronization (void)
Initializes the thread synchronization sub-system.
Used in task 6.
Definition at line 87 of file sync.c.
Referenced by initialize().
{
 /* In task 6, add code here. */
}
Variable Documentation
struct port port_table[MAX_NUMBER_OF_PORTS]
Array holding information all ports.
Definition at line 9 of file sync.c.
Referenced by allocate_port(), find_port(), and initialize_ports().