02333 Task 7: src/kernel/threadqueue.c File Reference
src/kernel/threadqueue.c File Reference
This file implements operations on thread queues.
#include "threadqueue.h"
Functions
void thread_queue_init (struct thread_queue *const queue_ptr)
Initialize a thread queue.
void thread_queue_enqueue (struct thread_queue *const queue_ptr, const int thread_index)
Enqueue one thread into the thread queue.
int thread_queue_dequeue (struct thread_queue *const queue_ptr)
Remove the head of the queue.
int thread_queue_is_empty (const struct thread_queue *const queue_ptr)
Checks if the queue is empty.
int thread_queue_head (const struct thread_queue *const queue_ptr)
Returns the first thread in the thread_queue.
Detailed Description
This file implements operations on thread queues.
Definition in file threadqueue.c.
Function Documentation
int thread_queue_dequeue (struct thread_queue *const queue_ptr)
Remove the head of the queue.
Returns:
the index, into thread_table, of the thread removed from the thread queue.
Parameters:
queue_ptr Points to the thread queue.
Definition at line 38 of file threadqueue.c.
References thread::data, thread_queue::head, thread::next, thread_queue::tail, thread_queue_is_empty(), and thread_table.
Referenced by keyboard_interrupt_handler().
{
 if (!thread_queue_is_empty(queue_ptr))
 {
  const register int thread_index=queue_ptr->head;
  /* The queue is not empty so we can remove one thread. */
  queue_ptr->head=thread_table[thread_index].data.next;
  if (thread_queue_is_empty(queue_ptr))
  {
   /* Make sure the tail is reset if the queue becomes empty. */
   queue_ptr->tail=-1;
  }
  return thread_index;
 }
 /* Return -1 if the queue was empty. */
 return -1;
}
void thread_queue_enqueue (struct thread_queue *const queue_ptr, const int thread_index)
Enqueue one thread into the thread queue.
The thread will be placed at the end of the queue.
Parameters:
queue_ptr Points to the thread queue.
thread_index Index, into thread_table, of the thread to be inserted into the thread queue.
Definition at line 15 of file threadqueue.c.
References thread::data, thread_queue::head, thread::next, thread_queue::tail, thread_queue_is_empty(), and thread_table.
Referenced by keyboard_interrupt_handler().
{
 /* Insert the thread as tail. */
 /* There is no next thread since the thread will be the new tail. */
 thread_table[thread_index].data.next=-1;
 if (thread_queue_is_empty(queue_ptr))
 {
  /* Set both head and tail if the queue is empty. */
  queue_ptr->head=thread_index;
  queue_ptr->tail=thread_index;
 }
 else
 {
  /* Replace the tail with the thread. */
  thread_table[queue_ptr->tail].data.next=thread_index;
  queue_ptr->tail=thread_index;
 }
}
int thread_queue_head (const struct thread_queue *const queue_ptr)
Returns the first thread in the thread_queue.
Returns:
the index, into thread_table, of the first thread in the thread_queue or -1 if the queue is empty.
Parameters:
queue_ptr Points to the thread queue.
Definition at line 66 of file threadqueue.c.
References thread_queue::head.
{
 return queue_ptr->head;
}
void thread_queue_init (struct thread_queue *const queue_ptr)
Initialize a thread queue.
Parameters:
queue_ptr Points to the thread queue to be initialized.
Definition at line 8 of file threadqueue.c.
References thread_queue::head, and thread_queue::tail.
Referenced by allocate_port(), and initialize().
{
 queue_ptr->head=-1;
 queue_ptr->tail=-1;
}
int thread_queue_is_empty (const struct thread_queue *const queue_ptr)
Checks if the queue is empty.
Returns:
1 if the queue is empty. Returns 0 otherwise.
Parameters:
queue_ptr Points to the thread queue.
Definition at line 60 of file threadqueue.c.
References thread_queue::head.
Referenced by keyboard_interrupt_handler(), thread_queue_dequeue(), and thread_queue_enqueue().
{
 return -1 == queue_ptr->head;
}