02333 Task 7: src/kernel/video.c File Reference
src/kernel/video.c File Reference
#include "kernel.h"
Functions
void clear_screen (void)
Clears the screen.
void kprints (const char *string)
Outputs a string to the bochs console.
void kprinthex (const register long value)
Prints a long formatted as a hexadecimal number to the bochs console.
Variables
struct screen *const screen_pointer = (struct screen*) 0xB8000
Points to the VGA screen.
Function Documentation
void clear_screen (void)
Clears the screen.
Clears the VGA buffer which is used in task 7.
Definition at line 7 of file video.c.
References screen_position::character, MAX_COLS, MAX_ROWS, screen::positions, and screen_pointer.
Referenced by initialize().
{
 register int row, column;
 for(row=0; row<MAX_ROWS; row++)
 {
  for(column=0; column<MAX_COLS; column++)
  {
   screen_pointer->positions[row][column].character=' ';
  }
 }
}
void kprinthex (const register long value)
Prints a long formatted as a hexadecimal number to the bochs console.
Parameters:
value The value to be written
Definition at line 42 of file video.c.
References outb().
Referenced by initialize(), and interrupt_dispatcher().
{
 const static char hex_helper[16]="0123456789abcdef";
 register int      i;
 /* Print each character of the hexadecimal number. This is a very inefficient
    way of printing hexadecimal numbers. It is, however, very compact in terms
    of the number of source code lines. */
 for(i=15; i>=0; i--)
 {
  outb(0xe9, hex_helper[(value>>(i*4))&15]);
 }
}
void kprints (const char *const string)
Outputs a string to the bochs console.
Parameters:
string Points to a null terminated string
Definition at line 23 of file video.c.
References outb().
Referenced by initialize(), interrupt_dispatcher(), and prepare_process().
{
 /* Loop until we have found the null character. */
 while(1)
 {
  register const char curr = *string++;
  if (curr)
  {
   outb(0xe9, curr);
  }
  else
  {
   return;
  }
 }
}
Variable Documentation
struct screen* const screen_pointer = (struct screen*) 0xB8000
Points to the VGA screen.
Definition at line 4 of file video.c.
Referenced by clear_screen().