<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://lameduck.dtu.ws/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="LameDuck" targetNamespace="http://lameduck.dtu.ws/" xmlns:bs="urn://types.fastmoney.imm.dtu.dk">
<wsdl:import namespace="http://lameduck.dtu.ws" location="LameDuck.wsdl"/>
<binding name="LameDuckBinding" type="tns:LameDuckPortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
        <operation name="getFlights">
            <soap:operation soapAction="getFlights_Action"/>
            <input name="input1">
                <soap:body use="literal" namespace="http://lameduck.dtu.ws/"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://lameduck.dtu.ws/"/>
            </output>
        </operation>
        <operation name="bookFlight">
            <soap:operation soapAction="bookFlight_Action"/>
            <input name="input2">
                <soap:body use="literal" namespace="http://lameduck.dtu.ws/"/>
            </input>
            <output name="output2">
                <soap:body use="literal" namespace="http://lameduck.dtu.ws/"/>
            </output>
            <fault name="fault2">
                <soap:fault name="fault2"/>
            </fault>
        </operation>
        <operation name="cancelFlight">
            <soap:operation soapAction="cancelFlight_Action"/>
            <input name="input3">
                <soap:body use="literal" namespace="http://lameduck.dtu.ws/"/>
            </input>
            <output name="output3">
                <soap:body use="literal" namespace="http://lameduck.dtu.ws/"/>
            </output>
            <fault name="fault1">
                <soap:fault name="fault1"/>
            </fault>
        </operation>
    </binding>
    <service name="LameDuckService">
        <port name="LameDuckPortType" binding="tns:LameDuckBinding">
            <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
        </port>
    </service>
</definitions>